title: "PeopleSoft"
theme: jekyll-theme-cayman

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S2-CS2103T-T11-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
